The data-size of ListAndWatch exceeds 4M.
volcano-sh/devices pull request #22
Opened 2022-04-02 10:11 UTC by bigclouds

Kubelet reports "grpc: received message larger than max".
It needs a strategic way to report device information.
Add a division factor,  by which  device amount is divided.

Signed-off-by: longguang.yue <bigclouds@163.com>

2022-04-23 03:08 UTC, Thor-wl commented
/cc @william-wang @tizhou86 Please help take a review. Thanks!

2022-05-03 09:54 UTC, shinytang6 requested changes
Just curious, when a pod request comes, should we also multiply the requested memory by factor?

According to my understanding, if it is assumed that device actual memory = 8192, factor = 256. After that pr, device memory will be 32. the corresponding pod request also needs to be changed. What l mean is in the allocate rpc, the pod request memory may also need to be multiplied by factor?

2022-05-21 12:14 UTC, bigclouds commented
Yes. Factor is the least allocation unit. Before this patch  the unit is 1M.
pod's request represents how many of this unit.

2022-05-23 07:38 UTC, shinytang6 requested changes
Overall it looks good to me, but l think documentation is required to tell the user that if factor is configured, the request of memory unit is changed

2022-05-23 07:38 UTC, shinytang6 commented on pkg/plugin/nvidia/server.go
>  				AllocatedGPUResource: fmt.Sprintf("%d", reqGPU),
Here the real memory allocation should be multiplied by factor

2022-05-25 02:26 UTC, WingkaiHo commented
I think factor conver of running pod (task) through annotations of pod and node
such as
- `pod.annotations.volcano.sh/gpu-factor` default is 1M
- `node.annotations.volcano.sh/gpu-factor` is setting by device plugin, such as 256M
- volcano scheduler calculate pod gpu usage : `volcano.sh/gpu-memory` *  (`pod.annotations.volcano.sh/gpu-factor` / `node.annotations.volcano.sh/gpu-factor` )

2022-07-28 09:38 UTC, shinytang6 commented
LGTM overall.
one nit: Let's take `100` as default factor and add doc for that, do you have time to modify that? @bigclouds

2022-08-19 12:34 UTC, closed without merging